"""Generate Action - Generate nginx configurations.

CONTRACT:
- read_only: True (writes to local filesystem, not server)
- requires_backup: False
- rollback_support: N/A
- prerequisites: None
"""

from dataclasses import dataclass
from pathlib import Path

from server_doctor.actions.report import ActionContract
from server_doctor.model.server import ProjectInfo, ProjectType, ServerBlock


class GenerateAction:
    """Generate nginx configuration files.

    This action generates config files locally.
    It does NOT write to the remote server.
    """

    CONTRACT = ActionContract(
        read_only=True,  # Only writes locally
        requires_backup=False,
        rollback_support=False,
        prerequisites=[],
    )

    def generate_laravel_config(
        self,
        project: ProjectInfo,
        domain: str,
        php_socket: str = "/run/php/php8.2-fpm.sock",
    ) -> str:
        """Generate nginx config for a Laravel project.

        Args:
            project: Project information.
            domain: Domain name for the site.
            php_socket: PHP-FPM socket path.

        Returns:
            Generated nginx configuration as string.
        """
        root = project.public_path or f"{project.path}/public"

        config = f'''# Generated by server-doctor
# Project: {project.path}
# Type: Laravel

server {{
    listen 80;
    listen [::]:80;
    server_name {domain};

    root {root};
    index index.php index.html;

    # Logging
    access_log /var/log/nginx/{domain}.access.log;
    error_log /var/log/nginx/{domain}.error.log;

    # Security: Block hidden files except .well-known
    location ~ /\\.(?!well-known).* {{
        deny all;
    }}

    # Laravel routing
    location / {{
        try_files $uri $uri/ /index.php?$query_string;
    }}

    # PHP-FPM
    location ~ \\.php$ {{
        fastcgi_pass unix:{php_socket};
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_hide_header X-Powered-By;
    }}

    # Static assets caching
    location ~* \\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {{
        expires 30d;
        add_header Cache-Control "public, immutable";
    }}
}}
'''
        return config

    def generate_static_config(self, project: ProjectInfo, domain: str) -> str:
        """Generate nginx config for a static site."""
        root = project.path

        config = f'''# Generated by server-doctor
# Project: {project.path}
# Type: Static

server {{
    listen 80;
    listen [::]:80;
    server_name {domain};

    root {root};
    index index.html index.htm;

    # Security: Block hidden files
    location ~ /\\. {{
        deny all;
    }}

    # Static routing
    location / {{
        try_files $uri $uri/ =404;
    }}

    # Caching
    location ~* \\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {{
        expires 30d;
        add_header Cache-Control "public, immutable";
    }}
}}
'''
        return config

    def write_config(self, config: str, output_path: Path) -> None:
        """Write configuration to a local file.

        Args:
            config: Configuration content.
            output_path: Path to write to.
        """
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(config)
